# -*- coding: utf-8 -*-
"""crawlData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKbvYT3Wq_fh39OgxHY8xbh_xQ4Gh-XJ

GetId
"""

import sys
import requests
import time
import random
import pandas as pd
from datetime import datetime

headers = {
    "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "vi-VN,vi;q=0.9,fr-FR;q=0.8,fr;q=0.7,en-US;q=0.6,en;q=0.5",
    "Referer": "https://tiki.vn/search?q=laptop",
    "X-guest-token" : "bdLuG1ftrqPW68Rn5YkDp3viXOAlMEUj",
    "Connection": "keep-alive",
    "TE" : "Trailers"
}

params = {
    "limit": 40,
    "include": "advertisement",
    "aggregations": "2",
    "trackity_id": "227472c2-2212-6e63-7d76-8cc5721fa8ce",
    "q": "laptop",
    "page": "1"
}

# 10. Nhận vào 2 thông số là đường dẫn lưu file và tên file
if len(sys.argv) < 3:
    # Nếu không đủ tham số, sử dụng giá trị mặc định
    # Lấy ngày hiện tại
    today = datetime.today().strftime('%d_%m_%Y')
    print("Không đủ tham số, sử dụng giá trị mặc định.")
    output_csv_path = "D:/"  # Thay bằng giá trị mặc định của bạn
    output_csv_file = f"manualData_{today}.csv"  # Thay bằng tên file đầu ra mặc định của bạn
else:
    output_csv_path = sys.argv[1]
    output_csv_file = sys.argv[2]


productId = []
for i in range(1, 11):
    params['page'] = i
    #https://tiki.vn/api/v2/products
    response = requests.get('https://tiki.vn/api/v2/products', headers=headers, params=params)
    if response.status_code == 200:
        print('request success!!!')
        for record in response.json().get('data'):
            productId.append({'id': record.get('id')})
    time.sleep(random.randrange(3, 10))

df = pd.DataFrame(productId)
df.to_csv(f'{output_csv_path}list_id_laptop.csv', index=False)

"""GetNecessoryData"""

import pandas as pd
import requests
import time
import random
from tqdm import tqdm
# _trackity:227472c2-2212-6e63-7d76-8cc5721fa8ce;
# TOKENS:{%22access_token%22:%22bdLuG1ftrqPW68Rn5YkDp3viXOAlMEUj%22%2C%22expires_in%22:157680000%2C%22expires_at%22:1883632213231%2C%22guest_token%22:%22bdLuG1ftrqPW68Rn5YkDp3viXOAlMEUj%22};
# delivery_zone:Vk4wMzkwMDYwMDE=; ?
# _gcl_gs:2.1.k1$i1725952209; ?
# _ga:GA1.1.2129758477.1725952214;
# _gcl_aw:GCL.1725952218.CjwKCAjw3P-2BhAEEiwA3yPhwEitOQeccxxsWFsbHJK6XxkQR-kUT8t_7wtKnJRzrahDnnBSeH6dmhoCetwQAvD_BwE; ?
# _gcl_au:1.1.238109599.1725952218;
# _hjSession_522327:eyJpZCI6IjdjYjA3YTM1LWNlMzQtNGZjNy1iOTQ1LWRhMjU3NWMwYjJlYiIsImMiOjE3MjU5NTIyMTgxNzcsInMiOjAsInIiOjAsInNiIjowLCJzciI6MCwic2UiOjAsImZzIjoxLCJzcCI6MH0=;
# _fbp:fb.1.1725952218939.230492170228353478;
# __uidac:0166dff0db5349e3b273216e8d635637;
# dtdz:c45f1ac1-bc00-5115-b2ae-fb6c46036403;
# __utm:source%3Dgoogle%7Cmedium%3Dcpc%7Ccampaign%3DSEA_NBR_GGL_PMA_DAP_ALL_VN_ALL_UNK_UNK_C.PMAX_X.21434089152_Y.165260184698_V._W.DT_A._O.CIR;
# __utm:source%3Dgoogle%7Cmedium%3Dcpc%7Ccampaign%3DSEA_NBR_GGL_PMA_DAP_ALL_VN_ALL_UNK_UNK_C.PMAX_X.21434089152_Y.165260184698_V._W.DT_A._O.CIR;
# __iid:749;
# __iid:749;
# __su:0;
# __su:0;
# __RC:5;
# __R:3;
# tiki_client_id:2129758477.1725952214;
# cto_bundle:fVKV-V9vS1UyTWV2RlZ3MVlYZTIyU2ozZUgyQjNLVlpEZiUyRlgwbTR3eFBrV1NqQ2VjM21tZU51SjJJcEIlMkZSNFgxJTJGbVRPV1I1bjR0MEc4Vmt6aWltR0ROaG5EbDZsVnBXelF4SHBwdVpuYlIlMkZwUUJZcnFzWkV2ajAlMkIlMkYlMkJvYmp5RHhLTnd1QmNLSkdsTFQ1NzJGMDFDVWF5dDlYQSUzRCUzRA;
# _hjSessionUser_522327:eyJpZCI6ImI1YzE3OGE0LTBhZGMtNTYyYi1hNjY3LWUxODM5MTc1Nzc1MSIsImNyZWF0ZWQiOjE3MjU5NTIyMTgxNzEsImV4aXN0aW5nIjp0cnVlfQ==;
# __adm_upl:eyJ0aW1lIjoxNzI1OTU0MDcxLCJfdXBsIjoiMC01MjAxMDU1NTU0MjQ3MTk4NzUxIn0=;
# __uif:__uid%3A5201055554247198751%7C__ui%3A-1%7C__create%3A1701055554;
# __tb:0;
# __IP:247169279;
# amp_99d374:f6wy3ljaOqwzrwJ6mnQpJy...1i7djvvgb.1i7dk7l45.2c.2j.4v;
# _ga_S9GLR1RQFJ:GS1.1.1725961346.2.0.1725961346.60.0.0
cookies = {
    'TIKI_GUEST_TOKEN': '8jWSuIDBb2NGVzr6hsUZXpkP1FRin7lY',
    'TOKENS': '{%22access_token%22:%22bdLuG1ftrqPW68Rn5YkDp3viXOAlMEUj%22%2C%22expires_in%22:157680000%2C%22expires_at%22:1883632213231%2C%22guest_token%22:%22bdLuG1ftrqPW68Rn5YkDp3viXOAlMEUj%22}',
    'TOKENS': '{%22access_token%22:%22bdLuG1ftrqPW68Rn5YkDp3viXOAlMEUj%22%2C%22expires_in%22:157680000%2C%22expires_at%22:1883632213231%2C%22guest_token%22:%22bdLuG1ftrqPW68Rn5YkDp3viXOAlMEUj%22}',
    'amp_99d374': 'eSc-_0HT1um7cb57E7dwA0...1enloc6a2.1enlohtdv.3.2.5',
    'amp_99d374_tiki.vn': 'eSc-_0HT1um7cb57E7dwA0...1enloc6a2.1enlocds8.0.1.1',
    '_gcl_au': '1.1.238109599.1725952218',
    '_ants_utm_v2': '',
    '_pk_id.638735871.2fc5': 'b92ae025fbbdb31f.1605974236.1.1605974420.1605974236.',
    '_pk_ses.638735871.2fc5': '*',
    '_trackity': '227472c2-2212-6e63-7d76-8cc5721fa8ce',
    '_ga_NKX31X43RV': 'GS1.1.1605974235.1.1.1605974434.0',
    '_ga': 'GA1.1.2129758477.1725952214',
    'ai_client_id': '11935756853.1605974227',
    'an_session': 'zizkzrzjzlzizqzlzqzjzdzizizqzgzmzkzmzlzrzmzgzdzizlzjzmzqzkznzhzhzkzdzhzdzizlzjzmzqzkznzhzhzkzdzizlzjzmzqzkznzhzhzkzdzjzdzhzqzdzizd2f27zdzjzdzlzmzmznzq',
    'au_aid': '11935756853',
    'dgs': '1605974411%3A3%3A0',
    'au_gt': '1605974227146',
    '_ants_services': '%5B%22cuid%22%5D',
    '__admUTMtime': '1605974236',
    '__iid': '749',
    '__su': '0',
    '_bs': 'bb9a32f6-ab13-ce80-92d6-57fd3fd6e4c8',
    '_gid': 'GA1.2.867846791.1605974237',
    '_fbp': 'fb.1.1725952218939.230492170228353478',
    '_hjid': 'f152cf33-7323-4410-b9ae-79f6622ebc48',
    '_hjFirstSeen': '1',
    '_hjIncludedInPageviewSample': '1',
    '_hjAbsoluteSessionInProgress': '0',
    '_hjIncludedInSessionSample': '1',
    'tiki_client_id': '657946765.1605974236',
    '__gads': 'ID=ae56424189ecccbe-227eb8e1d6c400a8:T=1605974229:RT=1605974229:S=ALNI_MZFWYf2BAjzCSiRNLC3bKI-W_7YHA',
    'proxy_s_sv': '1605976041662',
    'TKSESSID': '8bcd49b02e1e16aa1cdb795c54d7b460',
    'TIKI_RECOMMENDATION': '21dd50e7f7c194df673ea3b717459249',
    '_gat': '1',
    'cto_bundle': 'i6f48l9NVXNkQmJ6aEVLcXNqbHdjcVZoQ0k2clladUF2N2xjZzJ1cjR6WG43UTVaRmglMkZXWUdtRnJTNHZRbmQ4SDAlMkZwRFhqQnppRHFxJTJCSEozZXBqRFM4ZHVxUjQ2TmklMkJIcnhJd3luZXpJSnBpcE1nJTNE',
    'TIKI_RECENTLYVIEWED': '58259141',
    # '_trackity':'227472c2-2212-6e63-7d76-8cc5721fa8ce',
    # 'TOKENS':'{%22access_token%22:%22bdLuG1ftrqPW68Rn5YkDp3viXOAlMEUj%22%2C%22expires_in%22:157680000%2C%22expires_at%22:1883632213231%2C%22guest_token%22:%22bdLuG1ftrqPW68Rn5YkDp3viXOAlMEUj%22}',
    # 'delivery_zone':'Vk4wMzkwMDYwMDE=',
    # '_gcl_gs':'2.1.k1$i1725952209',
    # '_ga':'GA1.1.2129758477.1725952214',
    # '_gcl_aw':'GCL.1725952218.CjwKCAjw3P-2BhAEEiwA3yPhwEitOQeccxxsWFsbHJK6XxkQR-kUT8t_7wtKnJRzrahDnnBSeH6dmhoCetwQAvD_BwE',
    # '_gcl_au':'1.1.238109599.1725952218',
    # '_hjSession_522327':'eyJpZCI6IjdjYjA3YTM1LWNlMzQtNGZjNy1iOTQ1LWRhMjU3NWMwYjJlYiIsImMiOjE3MjU5NTIyMTgxNzcsInMiOjAsInIiOjAsInNiIjowLCJzciI6MCwic2UiOjAsImZzIjoxLCJzcCI6MH0=',
    # '_fbp':'fb.1.1725952218939.230492170228353478',
    # '__uidac':'0166dff0db5349e3b273216e8d635637',
    # 'dtdz':'c45f1ac1-bc00-5115-b2ae-fb6c46036403',
    # '__utm':'source%3Dgoogle%7Cmedium%3Dcpc%7Ccampaign%3DSEA_NBR_GGL_PMA_DAP_ALL_VN_ALL_UNK_UNK_C.PMAX_X.21434089152_Y.165260184698_V._W.DT_A._O.CIR',
    # '__utm':'source%3Dgoogle%7Cmedium%3Dcpc%7Ccampaign%3DSEA_NBR_GGL_PMA_DAP_ALL_VN_ALL_UNK_UNK_C.PMAX_X.21434089152_Y.165260184698_V._W.DT_A._O.CIR',
    # '__iid':'749',
    # '__iid':'749',
    # '__su':'0',
    # '__su':'0',
    # '__RC':'5',
    # '__R':'3',
    # 'tiki_client_id':'2129758477.1725952214',
    # 'cto_bundle':'fVKV-V9vS1UyTWV2RlZ3MVlYZTIyU2ozZUgyQjNLVlpEZiUyRlgwbTR3eFBrV1NqQ2VjM21tZU51SjJJcEIlMkZSNFgxJTJGbVRPV1I1bjR0MEc4Vmt6aWltR0ROaG5EbDZsVnBXelF4SHBwdVpuYlIlMkZwUUJZcnFzWkV2ajAlMkIlMkYlMkJvYmp5RHhLTnd1QmNLSkdsTFQ1NzJGMDFDVWF5dDlYQSUzRCUzRA',
    # '_hjSessionUser_522327':'eyJpZCI6ImI1YzE3OGE0LTBhZGMtNTYyYi1hNjY3LWUxODM5MTc1Nzc1MSIsImNyZWF0ZWQiOjE3MjU5NTIyMTgxNzEsImV4aXN0aW5nIjp0cnVlfQ==',
    # '__adm_upl':'eyJ0aW1lIjoxNzI1OTU0MDcxLCJfdXBsIjoiMC01MjAxMDU1NTU0MjQ3MTk4NzUxIn0=',
    # '__uif':'__uid%3A5201055554247198751%7C__ui%3A-1%7C__create%3A1701055554',
    # '__tb':'0' ,
    # '__IP':'247169279',
    # 'amp_99d374':'f6wy3ljaOqwzrwJ6mnQpJy...1i7djvvgb.1i7dk7l45.2c.2j.4v',
    # '_ga_S9GLR1RQFJ':'GS1.1.1725961346.2.0.1725961346.60.0.0',
    # '_gat': '1',
    # 'TIKI_RECENTLYVIEWED': '58259141',
    # 'TKSESSID': '8bcd49b02e1e16aa1cdb795c54d7b460',
}

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
    'Accept': 'application/json, text/plain, */*',
    'Accept-Language': 'vi-VN,vi;q=0.9,fr-FR;q=0.8,fr;q=0.7,en-US;q=0.6,en;q=0.5',
    'Referer': 'https://tiki.vn/may-tinh-xach-tay-laptop-dell-latitude-5470-intel-core-i5-6300-14-inch-hd-ram-8gb-256gb-ssd-intel-uhd-graphics-fedora-os-hang-chinh-hang-p222707075.html?itm_campaign=SRC_YPD_TKA_PLA_UNK_ALL_UNK_UNK_UNK_UNK_X.287415_Y.1869735_Z.3921284_CN.Product-Ads-22%2F02%2F2024&itm_medium=CPC&itm_source=tiki-ads&spid=270465750',
    'x-guest-token': 'bdLuG1ftrqPW68Rn5YkDp3viXOAlMEUj',
    'Connection': 'keep-alive',
    'TE': 'Trailers',
}

params = (
    ('platform', 'web'),
    ('spid', 270465750)
    # ('include', 'tag,images,gallery,promotions,badges,stock_item,variants,product_links,discount_tag,ranks,breadcrumbs,top_features,cta_desktop'),
)

def parser_product(json):
    try:
        d = {
            'id': json.get('id'),
            'sku': json.get('sku'),
            'product_name': json.get('name'),
            'short_description': json.get('short_description'),
            'price': json.get('price'),
            'discount': json.get('discount'),
            'discount_rate': json.get('discount_rate'),
            'review_count': json.get('review_count'),
            'order_count': json.get('order_count'),
            'inventory_status': json.get('inventory_status'),
            'is_visible': json.get('is_visible'),
            'stock_item_qty': json.get('stock_item', {}).get('qty', None),
            'brand_id': json.get('brand', {}).get('id', None),
            'brand_name': json.get('brand', {}).get('name', None)
        }
    except Exception as e:
        print(f"Lỗi khi phân tích dữ liệu sản phẩm: {e}")
        d = {}
    return d

# Đọc danh sách ID sản phẩm từ file CSV
df_id = pd.read_csv(f'{output_csv_path}list_id_laptop.csv')
p_ids = df_id.id.to_list()
print(p_ids)
result = []

# 11. Gọi API để lấy danh sách laptop và lưu vào file đã được khai báo với đường dẫn và tên file nhập vào
for pid in tqdm(p_ids, total=len(p_ids)):
    try:
        response = requests.get(f'https://tiki.vn/api/v2/products/{pid}', headers=headers, params=params, cookies=cookies)
        if response.status_code == 200:
            print(f'Crawl data {pid} success !!!')
            result.append(parser_product(response.json()))
        else:
            print(f'Lỗi khi lấy dữ liệu sản phẩm {pid}: HTTP {response.status_code}')
    except requests.exceptions.RequestException as e:
        print(f"Lỗi kết nối khi lấy dữ liệu sản phẩm {pid}: {e}")

    # Để tránh bị chặn, sử dụng thời gian ngủ ngẫu nhiên giữa các yêu cầu
    time.sleep(random.uniform(0.5, 2))

# Lưu dữ liệu đã crawl vào file CSV
df_product = pd.DataFrame(result)
# df_product.to_csv('crawled_data_laptop.csv', index=False)
df_product.to_csv(f'{output_csv_path}{output_csv_file}', sep=';', index=False)